name = "chatlabs"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
main = "index.ts"

[env.production]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
SUPABASE_SERVICE_ROLE_KEY = ""
OPENAI_API_KEY = ""
OPENAI_ORGANIZATION_ID = ""

[[routes]]
pattern = "/api/chat/tools-stream"
zone_name = "your-domain.com"
custom_domain = true

[build.upload]
format = "service-worker"